In [2]:
import sys
sys.path.append('../src')

import os
os.environ["LANGUAGE"] = 'ar'

from sqlalchemy.sql.expression import func
from wikidataDB import WikidataEntity, WikidataID, Session
from wikidataRetriever import WikidataKeywordSearch, AstraDBConnect
from SPARQLWrapper import SPARQLWrapper, JSON

import json
import os
import pandas as pd
from tqdm import tqdm
from concurrent.futures import ThreadPoolExecutor
import pickle
from datasets import load_dataset
import re
from requests.exceptions import HTTPError
import time
from tqdm import tqdm

def is_in_wikipedia(qid):
    item = WikidataID.get_id(qid)
    if item is None:
        return False
    return item.in_wikipedia

In [14]:
prep

,Sentence,Entity Name,Entity Span,Correct QID,Correct in Wikipedia,Language,Sentence no entity
0,Tropico 3 ist ein Wirtschaftssimulation und de...,Tropico 3,"[(0, 9), (184, 193)]",Q1316866,True,de,Entity ist ein Wirtschaftssimulation und der d...
1,"Das Add-on ""Tropico 3 – Absolute Power"" erschi...",Tropico 3,"[(12, 21), (192, 201)]",Q1316866,True,de,"Das Add-on ""Entity – Absolute Power"" erschien ..."
2,"The Oprah Winfrey Show, oft auch nur Oprah ode...",The Oprah Winfrey Show,"[(0, 22)]",Q694106,True,de,"Entity, oft auch nur Oprah oder kurz O genannt..."
3,"Laubsturm (Originaltitel: ""La Hojarasca"") ist ...",Laubsturm,"[(0, 9), (313, 322)]",Q1513486,True,de,"Entity (Originaltitel: ""La Hojarasca"") ist der..."
4,"Asterix (im Original: ""Astérix"") ist die 1959 ...",Asterix,"[(0, 7)]",Q42490,True,de,"Entity (im Original: ""Astérix"") ist die 1959 v..."
...,...,...,...,...,...,...,...
15441,Adobe Creative Suite是Adobe公司出品的集成了平面设计、视频编辑、网页...,Adobe Creative Suite,"[(0, 20)]",Q360118,True,zh,Entity是Adobe公司出品的集成了平面设计、视频编辑、网页设计等应用的产品套装。
15442,国际足球联合会（；），简称国际足联（），是管理英式足球、室内五人足球和沙滩足球的国际体育组织...,国际足球联合会,"[(0, 7)]",Q253414,True,zh,Entity（；），简称国际足联（），是管理英式足球、室内五人足球和沙滩足球的国际体育组织，...
15443,加拿大保守黨（；）是加拿大一個中間偏右政黨，于2003年12月7日由加拿大聯盟及加拿大進步保...,加拿大保守黨,"[(0, 6), (72, 78)]",Q488523,True,zh,Entity（；）是加拿大一個中間偏右政黨，于2003年12月7日由加拿大聯盟及加拿大進步保...
15444,噴火戰鬥機（），是英國在二次世界大戰中最重要也最具代表性的战斗机之一，也是最主要的單發動機戰...,噴火戰鬥機,"[(0, 5)]",Q29190,True,zh,Entity（），是英國在二次世界大戰中最重要也最具代表性的战斗机之一，也是最主要的單發動機...
15445,哈里亚纳邦（，拉丁字母转写：）是印度北部的一个邦，1966年11月1日从旁遮普邦划分出来。,哈里亚纳邦,"[(0, 5)]",Q1174,True,zh,Entity（，拉丁字母转写：）是印度北部的一个邦，1966年11月1日从旁遮普邦划分出来。

In [15]:
prep = pickle.load(open(f"../data/Evaluation Data/REDFM/processed_dataframe.pkl", "rb"))
sample_ids = pickle.load(open(f"../data/Evaluation Data/Sample IDs (AR EN DE).pkl", "rb"))

sample_prep = prep.apply(lambda x: x['Correct QID'] in sample_ids['QID'].values, axis=1)

In [ ]:
import numpy as np
import pickle

def calculate_mrr_score(df, pred_col, true_cols):
    # Remove duplicate QIDs while keeping the order
    prep[pred_col] = prep[pred_col].apply(lambda x: list(dict.fromkeys(x)))
    # Get the rank of each retrieved QID
    ranks = df.apply(lambda x: [i+1 for i in range(len(x[pred_col])) if (x[pred_col][i] in x[true_cols])], axis=1)
    # Return the MRR
    return ranks.apply(lambda x: 1/x[0] if len(x)>0 else 0).mean()

def calculate_ndcg_score(df, pred_col, true_cols):
    # Remove duplicate QIDs while keeping the order
    prep[pred_col] = prep[pred_col].apply(lambda x: list(dict.fromkeys(x)))
    # Get the rank of each retrieved QID
    ranks = df.apply(lambda x: [i+1 for i in range(len(x[pred_col])) if (x[pred_col][i] in x[true_cols])], axis=1)
    # Calculate the DCG, the Ideal DCG and finally return the NDCG
    dcg = ranks.apply(lambda x: sum([1/np.log2(y+1) for y in x]) if len(x)>0 else 0)
    idcg = df.apply(lambda x: sum([1/np.log2(y+1) for y in range(1, min(len(x[true_cols]), len(x[pred_col])) + 1)]), axis=1)
    return (dcg/idcg).mean()

collection = "wikidata_test_v1"
evaluation_dataset = "REDFM"
filename = f"retrieval_results_{evaluation_dataset}-{collection}-ar_DB-AR_EN_DE_Query-AR"
# filename = "retrieval_results_Mintaka-wikidata_langtest-en_DB(ar,en,de)_Query(en)"
prep = pickle.load(open(f"../data/Evaluation Data/Language Results/REDFM-withentity/{filename}.pkl", "rb"))
assert pd.isna(prep['Retrieval QIDs']).sum() == 0, "Evaluation not complete"

# For Mintaka, LC_QuAD, and RuBQ
# prep = prep[prep.apply(lambda x: all(x['Question in Wikipedia'] + x['Answer in Wikipedia']), axis=1)]
# prep['Correct QIDs'] = prep.apply(lambda x: x['Question QIDs'] + x['Answer QIDs'], axis=1)

# For REDFM
prep = prep[prep['Correct in Wikipedia']]
prep['Correct QIDs'] = prep['Correct QID'].apply(lambda x: [x])

print("MRR:")
print(calculate_mrr_score(prep, 'Retrieval QIDs', 'Correct QIDs'))
print("NDCG:")
print(calculate_ndcg_score(prep, 'Retrieval QIDs', 'Correct QIDs'))

MRR:
0.7009917368335837
NDCG:
0.6343382709738831

In [4]:
prep

,Question QIDs,Answer QIDs,Question in Wikipedia,Answer in Wikipedia,Question,Answer,Answer Type,Language,Retrieval QIDs,Retrieval Score
2,"[Q1497, Q846570]",[Q7245],"[True, True]",[True],Wer war ein berühmter amerikanischer Schriftst...,Mark Twain,entity,de,"[Q1131648, Q863037, Q23434, Q183565, Q1249322,...","[0.7361737, 0.7252581, 0.71197546, 0.7102274, ..."
11,"[Q133313, Q19020]",[],"[True, True]",[],Für wie viele Oscars ist Jake Gyllenhaal nomin...,1,numerical,de,"[Q133313, Q181883, Q181883, Q103916, Q103916, ...","[0.78086054, 0.7124473, 0.70858896, 0.7068757,..."
20,"[Q2121062, Q33240]",[Q33240],"[True, True]",[True],Wer ist älter: The Weeknd oder Drake?,Drake,entity,de,"[Q33240, Q33240, Q2121062, Q2121062, Q6078, Q2...","[0.75167465, 0.7485856, 0.731126, 0.7244818, 0..."
29,[Q22686],[],[True],[],Wie viele Kinder hat Donald Trump?,5,numerical,de,"[Q22686, Q22686, Q22686, Q22686, Q12071552, Q4...","[0.7468444, 0.7425915, 0.7359469, 0.7355348, 0..."
38,"[Q474573, Q1060306]",[],"[True, True]",[],Heißt die Hauptfigur in Final Fantasy IX Kuja?,No,boolean,de,"[Q1060306, Q474573, Q223381, Q1334722, Q179859...","[0.8833048, 0.77215797, 0.76602125, 0.7638614,..."
...,...,...,...,...,...,...,...,...,...,...
179957,[Q736865],[Q588289],[True],[True],In welcher Art von Spiel ist Zeus der Herrsche...,city building,entity,de,"[Q736865, Q34201, Q34201, Q34201, Q41484, Q189...","[0.8017546, 0.7837493, 0.7689873, 0.76161915, ..."
179966,[Q2299192],[],[True],[],Wie viele Spiele von Impressions Games wurden ...,2,numerical,de,"[Q2299192, Q1767176, Q644793, Q59756366, Q1154...","[0.77015066, 0.73754334, 0.72979355, 0.7269815..."
179975,"[Q2299192, Q588289]",[Q510054],"[True, True]",[True],"Welches ist das neueste City Building Game, da...",Emperor: Rise of the Middle Kingdom,entity,de,"[Q917647, Q2299192, Q1767176, Q24050047, Q2405...","[0.7577782, 0.75268364, 0.7438443, 0.740633, 0..."
179984,[Q42310881],[],[True],[],Was ist der teuerste Fisch in „Animal Crossing...,"King Koi, King Red Snapper",entity,de,"[Q123141, Q754164, Q234014, Q771046, Q584064, ...","[0.70695496, 0.6790948, 0.67456937, 0.6741402,..."
179993,[Q8409],[Q217414],[True],[True],Wo ist die erste Ehefrau von Alexander dem Gro...,Amphipolis,entity,de,"[Q223134, Q190055, Q8409, Q8409, Q240145, Q416...","[0.82951677, 0.8193434, 0.8138453, 0.7945324, ..."

In [ ]:
from wikidataDB import WikidataEntity
from wikidataEmbed import WikidataTextifier, JinaAIReranker

collection = "wikidata_test_v1"
evaluation_dataset = "Mintaka"
filename = f"retrieval_results_{evaluation_dataset}-{collection}-de_DB-EN_Query-DE"
prep = pickle.load(open(f"../data/Evaluation Data/{filename}.pkl", "rb"))

textifier = WikidataTextifier(with_claim_aliases=False, with_property_aliases=False, language='en')
reranker = JinaAIReranker()

def rerank_qids(query, qids, reranker, textifier):
    entities = [WikidataEntity.get_entity(qid) for qid in qids]
    texts = [textifier.entity_to_text(entity) for entity in entities]
    scores = reranker.rank(query, texts)

    score_zip = zip(scores, prep.iloc[0]['Retrieval QIDs'])
    score_zip = sorted(score_zip, key=lambda x: -x[0])
    return [x[1] for x in score_zip]

scores = rerank_qids(prep.iloc[0]['Question'], prep.iloc[0]['Retrieval QIDs'], reranker, textifier)

tokenizer_config.json:   0%|          | 0.00/1.15k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/17.1M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/964 [00:00<?, ?B/s]

In [14]:
filename = f"retrieval_results_{evaluation_dataset}-{collection}-en_DB-EN_Query-EN"
prep = pickle.load(open(f"../data/Evaluation Data/{filename}.pkl", "rb"))
prep

,Question QIDs,Answer QIDs,Question in Wikipedia,Answer in Wikipedia,Question,Answer,Answer Type,Language,Retrieval QIDs,Retrieval Score
0,"[Q1497, Q846570]",[Q7245],"[True, True]",[True],What man was a famous American author and also...,Mark Twain,entity,en,"[Q1131648, Q1249322, Q863037, Q23434, Q7846597...","[0.7380401, 0.7190001, 0.71705467, 0.7165503, ..."
9,"[Q133313, Q19020]",[],"[True, True]",[],How many Academy Awards has Jake Gyllenhaal be...,1,numerical,en,"[Q181883, Q2665878, Q518675, Q181883, Q5887360...","[0.70622474, 0.7047322, 0.70396847, 0.70157534..."
18,"[Q2121062, Q33240]",[Q33240],"[True, True]",[True],"Who is older, The Weeknd or Drake?",Drake,entity,en,"[Q33240, Q33240, Q2121062, Q2121062, Q6078, Q2...","[0.7515571, 0.747073, 0.72907823, 0.7220057, 0..."
27,[Q22686],[],[True],[],How many children did Donald Trump have?,5,numerical,en,"[Q22686, Q22686, Q22686, Q22686, Q12071552, Q2...","[0.7423017, 0.73196423, 0.7283923, 0.72393155,..."
36,"[Q474573, Q1060306]",[],"[True, True]",[],Is the main hero in Final Fantasy IX named Kuja?,No,boolean,en,"[Q1060306, Q474573, Q1334722, Q223381, Q179859...","[0.8902929, 0.77739924, 0.7597104, 0.75929916,..."
...,...,...,...,...,...,...,...,...,...,...
179955,[Q736865],[Q588289],[True],[True],What kind of game is Zeus Master of Olympus?,city building,entity,en,None,None
179964,[Q2299192],[],[True],[],How many games by Impressions Games were relea...,2,numerical,en,None,None
179973,"[Q2299192, Q588289]",[Q510054],"[True, True]",[True],What is the newest city building game develope...,Emperor: Rise of the Middle Kingdom,entity,en,None,None
179982,[Q42310881],[],[True],[],What is the most expensive fish in Animal Cros...,"King Koi, King Red Snapper",entity,en,None,None
179991,[Q8409],[Q217414],[True],[True],Where did the first wife of Alexander the Grea...,Amphipolis,entity,en,None,None

In [ ]:
import pickle
import numpy as np

def calculate_accuracy_score(df):
    highest_score_idx = df['Retrieval Score'].apply(np.argmax)
    top_qid = df.apply(lambda x: x['Retrieval QIDs'][highest_score_idx[x.name]], axis=1)
    return (top_qid == df['Correct QID']).mean()

def calculate_log_odds_ratio_score(df):
    def log_odds_ratio(row):
        correct_qid = row['Correct QID']
        wrong_qid = row['Wrong QID']

        # Find the maximum scores for the correct and wrong QIDs
        correct_scores = [score for qid, score in zip(row['Retrieval QIDs'], row['Retrieval Score']) if qid == correct_qid]
        wrong_scores = [score for qid, score in zip(row['Retrieval QIDs'], row['Retrieval Score']) if qid == wrong_qid]

        max_correct_score = max(correct_scores, default=0)
        max_wrong_score = max(wrong_scores, default=0)

        correct_log_odds = np.log(max_correct_score / (1 - max_correct_score))
        wrong_log_odds = np.log(max_wrong_score / (1 - max_wrong_score))
        return correct_log_odds - wrong_log_odds

    # Apply the log odds ratio calculation to each row
    return df.apply(log_odds_ratio, axis=1).mean()

collection = "wikidata_test_v2"
evaluation_dataset = "Wikidata-Disamb"
prep = pickle.load(open(f"../data/Evaluation Data/retrieval_results_{evaluation_dataset}-{collection}-en.pkl", "rb"))
assert pd.isna(prep['Retrieval QIDs']).sum() == 0, "Evaluation not complete"

calculate_accuracy_score(prep)

In [ ]:
import matplotlib.pyplot as plt

def calculate_accuracy_over_K(df, pred_col, true_cols):
    # Remove duplicate QIDs while keeping the order
    prep[pred_col] = prep[pred_col].apply(lambda x: list(dict.fromkeys(x)))
    # Get the rank of each retrieved QID
    ranks = df.apply(lambda x: [i+1 for i in range(len(x[pred_col])) if (x[pred_col][i] in x[true_cols])], axis=1)
    ranks = ranks.apply(lambda x: min(x) if len(x) > 0 else None)

    accuracy = [(ranks <= i).mean() for i in range(int(ranks.max()))]
    return accuracy

collection = "wikidata_test_v1"
evaluation_dataset = "REDFM"
prep = pickle.load(open(f"../data/Evaluation Data/retrieval_results_{evaluation_dataset}-{collection}-en.pkl", "rb"))
assert pd.isna(prep['Retrieval QIDs']).sum() == 0, "Evaluation not complete"
prep = prep[prep['Correct in Wikipedia']]
prep['Correct QIDs'] = prep['Correct QID'].apply(lambda x: [x])

accuracy_v1 = calculate_accuracy_over_K(prep, 'Retrieval QIDs', 'Correct QIDs')

collection = "wikidata_test_v2"
evaluation_dataset = "REDFM"
prep = pickle.load(open(f"../data/Evaluation Data/retrieval_results_{evaluation_dataset}-{collection}-en.pkl", "rb"))
assert pd.isna(prep['Retrieval QIDs']).sum() == 0, "Evaluation not complete"
prep = prep[prep['Correct in Wikipedia']]
prep['Correct QIDs'] = prep['Correct QID'].apply(lambda x: [x])

accuracy_v2 = calculate_accuracy_over_K(prep, 'Retrieval QIDs', 'Correct QIDs')

# Create a simple bar chart
plt.plot(list(range(len(accuracy_v1))), np.array(accuracy_v1)*100, label='Jina')
plt.plot(list(range(len(accuracy_v2))), np.array(accuracy_v2)*100, label='Nvidia')
plt.title('Accuracy of 1 correct item in REDFM')
plt.xlabel('# Entities Retrieved')
plt.ylabel('Accuracy %')
plt.legend()

# Show the chart
plt.show()

In [ ]:
from sqlalchemy.sql import func
from tqdm import tqdm

# Modified query with random ordering
sample_count = sample_ids['from Evaluation'].sum()*2 - (~sample_ids['from Evaluation']).sum()
with tqdm(total=sample_count) as progressbar:
    with Session() as session:
        entities = (
            session.query(WikidataID)
            .filter(WikidataID.in_wikipedia == True)
            .order_by(func.random())  # Adds random ordering
            .yield_per(1000)
        )

        # Example of iterating through the entities
        for entity in tqdm(entities):
            if entity.id not in sample_ids['QID'].values:
                sample_ids = pd.concat([sample_ids, pd.DataFrame([{
                        'QID': entity.id,
                        'from Evaluation': False,
                        'In Wikipedia': True,
                        'Sample 2': True
                    }])], ignore_index=True)
                progressbar.update(1)
            if progressbar.n >= sample_count:
                break

In [ ]:
import pickle

# prep = pickle.load(open("/home/philippe.saade/GitHub/WikidataTextEmbedding/data/Evaluation Data/KGConv/processed_dataframe.pkl", "rb"))

sample_ids = pickle.load(open("../data/Evaluation Data/Sample IDs (EN).pkl", "rb"))
sample_ids = sample_ids[sample_ids['In Wikipedia']]

sample_qids_set = set(sample_ids['QID'].values)

# Use vectorized operations for 'not_in_sample'
# prep['Question in Wikipedia'] = prep['Question QID'].isin(sample_qids_set)
# prep['Answer in Wikipedia'] = prep['Answer QID'].isin(sample_qids_set)
# prep

In [ ]:
sample_ids[sample_ids['Sample 2']]

In [ ]:
for _, row in tqdm(prep.iterrows()):
    for i in range(len(row['Answer QIDs'])):
        if row['Answer in Wikipedia'][i] and row['Answer QIDs'][i] not in sample_qids_set:
            sample_ids = pd.concat([sample_ids, pd.DataFrame([{
                'QID': row['Answer QIDs'][i],
                'from Evaluation': True,
                'In Wikipedia': True,
                'from Evaluation 2': True
            }])], ignore_index=True)

In [ ]:
def remove_spans(sentence, spans, replace_with='Entity'):
    # Sort spans in ascending order to remove from left to right
    spans = sorted(spans, key=lambda x: x[0])
    offset = 0  # To track the shift in index after replacing each span

    for start, end in spans:
        sentence = sentence[:start - offset] + replace_with + sentence[end - offset:]
        offset += (end - start) - len(replace_with)  # Update offset to account for the replaced span length

    return sentence

data['Sentence no entity'] = data.apply(lambda x: remove_spans(x['Sentence'], x['Entity Span']), axis=1)